/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: mghu5jMIT32iMzClDAWn7rbe7oWzBC3Syo5ySwCVaIfm/iZDHs6VyVQDaP8HJlfkB1KtXiu2b0HPTtuUCxMfOQ==
 */

/* eslint-disable */
// tslint:disable

interface DatabaseSchema {}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export { serializeValue };
